### ISSUE TITLE
Support links w/o going through the search page

### ISSUE THREAD

**Issue by misfo** [kudos/combine.fm#13]
I might not understand exactly how your app works, so just set me straight if I'm way off base here...

Because there's a pretty straight-forward conversion from open.spotify.com URLs to match.audio URLs, I thought I'd be able to infer the match.audio URL. This would be super handy because a chat bot could detect an open.spotify.com URL and respond with the inferred match.audio URL. All of that could happen without hitting the match.audio server. So there'd be no need for a API endpoint like discussed in #11.

This doesn't work at the moment unless the spotify URL has been searched for already. So there appears to be some server-side work that needs to happen before a match.audio URL is useful. Could this server side work lazily the first time a match.audio URL is hit?

I'd be happy to take a crack at this if it's not a batshit crazy idea.

Thanks for the project, by the way. I'm surprised how well you got the matching to work... :+1:

**Comment by kudos** [comment]
It should actually work lazily, if it doesn't it's a bug. I'll have to investigate later.

**Comment by misfo** [comment]
Going to https://match.audio/spotify/track/3PnEn4pp5hZ7KovNzLGP3o, for instance, gets me this:
![screen shot 2015-08-20 at 10 24 03 am](https://cloud.githubusercontent.com/assets/40791/9387352/c2f2c70c-4725-11e5-9e6d-1c1b018cd066.png)

**Comment by kudos** [comment]
This got nuked as part of the Koa refactor, I needed to simplify things at the time and intended to add it back. I guess I forgot :D
